# Generated by Django 4.1.5 on 2023-01-31 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Platoon',
            fields=[
                ('platoon_number', models.IntegerField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=40)),
                ('patronymic', models.CharField(max_length=40)),
                ('military_rank', models.CharField(max_length=20)),
                ('military_post', models.CharField(max_length=255)),
                ('cycle', models.CharField(max_length=255)),
                ('login', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=255)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=40)),
                ('patronymic', models.CharField(max_length=40)),
                ('sex', models.CharField(max_length=10)),
                ('military_post', models.CharField(max_length=255)),
                ('login', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('group_number', models.IntegerField()),
                ('active', models.CharField(max_length=30)),
                ('platoon', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.platoon')),
            ],
        ),
        migrations.AddField(
            model_name='platoon',
            name='tutor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='users.teacher'),
        ),
    ]
