# Generated by Django 4.1.7 on 2023-04-01 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platoon',
            name='year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='group_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='teacher_role',
            field=models.IntegerField(null=True),
        ),
    ]
