# Generated by Django 4.1.5 on 2023-01-31 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platoon',
            name='status',
            field=models.CharField(default='учится', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='role',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
