# Generated by Django 4.1.6 on 2023-05-18 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platoon',
            name='order_of_enrollment',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='birth_year',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='marital_status',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='order_of_expulsion',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='phone_number',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='public_load',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='sports_category',
            field=models.CharField(default='нет', max_length=100),
        ),
    ]
