# Generated by Django 4.1.7 on 2023-02-17 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_platoon_status_teacher_role'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='platoon',
            table='platoons',
        ),
        migrations.AlterModelTable(
            name='student',
            table='students',
        ),
        migrations.AlterModelTable(
            name='teacher',
            table='teachers',
        ),
    ]
