# Generated by Django 4.1.7 on 2023-02-21 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_platoon_table_alter_student_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='status',
            field=models.CharField(max_length=30),
        ),
    ]
