# Generated by Django 4.1.7 on 2023-05-11 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platoon',
            name='tutor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='users.teacherprofile'),
        ),
    ]
