# Generated by Django 4.1.7 on 2023-05-11 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_platoon_tutor'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='studentprofile',
            table='students',
        ),
        migrations.AlterModelTable(
            name='teacherprofile',
            table='teachers',
        ),
    ]
