# Generated by Django 4.1.7 on 2023-05-11 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_studentprofile_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='military_post',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='patronymic',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='military_post',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='patronymic',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
