# Generated by Django 4.1.6 on 2023-05-11 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_studentprofile_military_post_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.IntegerField()),
                ('direction', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'course_directions',
            },
        ),
        migrations.AddField(
            model_name='platoon',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.coursedirection'),
        ),
    ]
