# Generated by Django 4.1.6 on 2023-05-14 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_studentprofile_name_studentprofile_surname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platoon',
            name='study_day',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
