# Generated by Django 4.1.3 on 2022-11-27 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demoproject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalCeil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.IntegerField()),
                ('attendance', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Platoon',
            fields=[
                ('platoon_number', models.IntegerField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=40)),
                ('patronymic', models.CharField(max_length=40)),
                ('sex', models.CharField(max_length=10)),
                ('military_post', models.CharField(max_length=255)),
                ('login', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('group_number', models.IntegerField()),
                ('active', models.CharField(max_length=30)),
                ('platoon_number', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='demoproject.platoon')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hours_count', models.IntegerField()),
                ('form', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('theme_number', models.IntegerField()),
                ('theme_name', models.CharField(max_length=255)),
                ('class_number', models.IntegerField()),
                ('class_name', models.CharField(max_length=255)),
                ('class_type', models.CharField(max_length=30)),
                ('classroom', models.IntegerField()),
                ('platoon', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='demoproject.platoon')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='demoproject.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=40)),
                ('patronymic', models.CharField(max_length=40)),
                ('military_rank', models.CharField(max_length=20)),
                ('military_post', models.CharField(max_length=255)),
                ('cycle', models.CharField(max_length=255)),
                ('login', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.AddField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demoproject.teacher'),
        ),
        migrations.AddField(
            model_name='platoon',
            name='tutor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='demoproject.teacher'),
        ),
        migrations.AddField(
            model_name='journalceil',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='demoproject.student'),
        ),
        migrations.AddField(
            model_name='journalceil',
            name='subject_class',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='demoproject.subjectclass'),
        ),
    ]
