# Generated by Django 4.1.5 on 2023-01-27 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoproject', '0002_journalceil_platoon_student_subject_subjectclass_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='status',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
