# Generated by Django 4.1.5 on 2023-01-27 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demoproject', '0003_teacher_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='platoon_number',
        ),
        migrations.AddField(
            model_name='student',
            name='platoon',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='demoproject.platoon'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subject',
            name='teacher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='demoproject.teacher'),
        ),
    ]
