# Generated by Django 4.1.5 on 2023-01-31 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('demoproject', '0005_alter_subject_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='platoon',
        ),
        migrations.AlterField(
            model_name='journalceil',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.student'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.teacher'),
        ),
        migrations.AlterField(
            model_name='subjectclass',
            name='platoon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.platoon'),
        ),
        migrations.DeleteModel(
            name='Platoon',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
