# Generated by Django 4.1.5 on 2023-02-02 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoproject', '0006_remove_student_platoon_alter_journalceil_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='subjectclass',
            name='platoon',
        ),
        migrations.RemoveField(
            model_name='subjectclass',
            name='subject',
        ),
    ]
