# Generated by Django 4.1.5 on 2023-02-02 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demoproject', '0007_remove_subject_teacher_remove_subjectclass_platoon_and_more'),
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalceil',
            name='subject_class',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='timetable.subjectclass'),
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='SubjectClass',
        ),
    ]
