# Generated by Django 4.1.6 on 2023-05-14 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalCeil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.IntegerField()),
                ('attendance', models.CharField(default='', max_length=10)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.studentprofile')),
                ('subject_class', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='timetable.subjectclass')),
            ],
            options={
                'db_table': 'journal_ceils',
            },
        ),
    ]
