# Generated by Django 4.1.7 on 2023-04-01 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JournalCeil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.IntegerField()),
                ('attendance', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'journal_ceils',
            },
        ),
    ]
