# Generated by Django 4.1.6 on 2023-02-10 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_platoon_status_teacher_role'),
        ('timetable', '0003_rename_date_subjectclass_class_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalCeil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.IntegerField()),
                ('attendance', models.CharField(max_length=10)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.student')),
                ('subject_class', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='timetable.subjectclass')),
            ],
        ),
    ]
