# Generated by Django 4.1.7 on 2023-02-17 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='journalceil',
            table='journal_ceils',
        ),
    ]
