# Generated by Django 4.1.7 on 2023-04-01 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('marks', '0003_alter_journalceil_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalceil',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.student'),
        ),
    ]
