# Generated by Django 4.1.6 on 2023-05-14 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hours_count', models.IntegerField()),
                ('form', models.CharField(max_length=15)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.teacherprofile')),
            ],
            options={
                'db_table': 'subjects',
            },
        ),
        migrations.CreateModel(
            name='SubjectClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_date', models.DateTimeField()),
                ('theme_number', models.IntegerField()),
                ('theme_name', models.CharField(max_length=255)),
                ('class_number', models.IntegerField()),
                ('class_name', models.CharField(max_length=255)),
                ('class_type', models.CharField(max_length=30)),
                ('classroom', models.IntegerField()),
                ('platoon', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.platoon')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='timetable.subject')),
            ],
            options={
                'db_table': 'subject_classes',
            },
        ),
        migrations.CreateModel(
            name='DirectionsSubjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.coursedirection')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.subject')),
            ],
            options={
                'db_table': 'directions_subjects',
                'unique_together': {('course_direction', 'subject')},
            },
        ),
    ]
