# Generated by Django 4.1.5 on 2023-02-02 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_platoon_status_teacher_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hours_count', models.IntegerField()),
                ('form', models.CharField(max_length=15)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('theme_number', models.IntegerField()),
                ('theme_name', models.CharField(max_length=255)),
                ('class_number', models.IntegerField()),
                ('class_name', models.CharField(max_length=255)),
                ('class_type', models.CharField(max_length=30)),
                ('classroom', models.IntegerField()),
                ('platoon', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.platoon')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='timetable.subject')),
            ],
        ),
    ]
