# Generated by Django 4.1.7 on 2023-04-01 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectclass',
            name='platoon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.platoon'),
        ),
        migrations.AddField(
            model_name='subjectclass',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='timetable.subject'),
        ),
        migrations.AddField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.teacher'),
        ),
    ]
