# Generated by Django 4.1.5 on 2023-02-02 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_alter_subjectclass_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjectclass',
            old_name='date',
            new_name='class_date',
        ),
    ]
