# Generated by Django 4.1.7 on 2023-05-11 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_platoon_year_alter_studentprofile_group_number_and_more'),
        ('timetable', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.teacherprofile'),
        ),
    ]
