# Generated by Django 4.1.7 on 2023-02-17 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_rename_date_subjectclass_class_date'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='subject',
            table='subjects',
        ),
        migrations.AlterModelTable(
            name='subjectclass',
            table='subject_classes',
        ),
    ]
