# Generated by Django 4.1.6 on 2023-05-11 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_alter_subject_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.IntegerField()),
                ('direction', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'course_directions',
            },
        ),
        migrations.CreateModel(
            name='DirectionsSubjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.coursedirection')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.subject')),
            ],
            options={
                'db_table': 'directions_subjects',
                'unique_together': {('course_direction', 'subject')},
            },
        ),
    ]
