# Generated by Django 4.1.6 on 2023-05-11 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_coursedirection_platoon_course'),
        ('timetable', '0004_coursedirection_directionssubjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directionssubjects',
            name='course_direction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.coursedirection'),
        ),
        migrations.DeleteModel(
            name='CourseDirection',
        ),
    ]
